### ISSUE TITLE
missing some files

### ISSUE THREAD

**Issue by handsomelys** [MZ-MiaoZhang/DRLK#1]
I'd like to follow up on your interesting work. But I tried to run your script in the README and found that it got an error: FileNotFoundError: [Errno 2] No such file or directory: './data/ddb/ent_emb.npy'. Pls can you give me the corresponding npy file.

**Comment by MZ-MiaoZhang** [comment]
Thanks for your interest in our work, you can download them from [google drive ](https://drive.google.com/drive/folders/1Q0GaDKWMvbkqbisgRbckxW5jTmZs5ViK?usp=sharing)
